# Generated by Django 3.0.3 on 2020-02-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200223_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='The date & time this article was published', null=True, unique_for_date='published'),
        ),
    ]
