# Generated by Django 3.0.3 on 2020-04-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_contact_photo_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, help_text='A banner image for the post', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo_contest',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload your image here', null=True, upload_to=''),
        ),
    ]
