# Generated by Django 3.0.3 on 2020-04-05 02:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
